### ISSUE TITLE
InstanceLayers loop is wrong in CreateInstance

### ISSUE THREAD

**Issue by simondeschenes** [ConfettiFX/The-Forge#92]
This is the code :
```for (uint32_t i = -1; i < pRenderer->mInstanceLayers.size(); ++i)```

It is initializing an unsigned integer to -1, which means it is initialized to UINT32_MAX.
It won't ever be lower than mInstanceLayers.size() and the loop will never be taken.

https://github.com/ConfettiFX/The-Forge/blob/d3b5c2994125dea006f0ef6d62bb09670c52396a/Common_3/Renderer/Vulkan/Vulkan.cpp#L1893

**Comment by simondeschenes** [comment]
Effectively, if we re-enable that code by initializing i to 0, then we get another problem because this line is commented :

```//gVkWantedInstanceExtensions[k] = "";```

Which means that `VK_EXT_debug_report` is both in the `VK_LAYER_LUNARG_standard_validation` and the "nullptr" layer (second loop) as the standard validation layer is implicitly enabled.

The only way to fix when we require `VK_EXT_debug_report` is to uncomment that line again.

**Comment by AntoineConffx** [comment]
@simondeschenes 
We just merged a fix for the loop index but we weren't able to reproduce the second part of this issue.
Could you give us repro steps? 
Also, could you try it out after the latest merge?
Thanks

**Comment by simondeschenes** [comment]
You need to comment `#define USE_DEBUG_UTILS_EXTENSION` inside of `Vulkan.cpp`.
That way, it will want to use `VK_EXT_DEBUG_REPORT_EXTENSION_NAME` instead of `VK_EXT_DEBUG_UTILS_EXTENSION_NAME` .

If you do, and have the first loop fixed, you will get `VK_EXT_debug_utils` 2 times in the `gVkInstanceExtensions` array (member of `pRenderer`).

I believe this commented code (because of the comment) was supposed to address this issue :
```// clear wanted extenstion so we dont load it more then once
//gVkWantedInstanceExtensions[k] = "";```

However, it is not right because it modifies `gVkWantedInstanceExtensions` instead of the local `wantedInstanceExtensions` array.

This is why the code should now read :
```// clear wanted extenstion so we don't load it more then once
wantedInstanceExtensions[k] = "";```

in both loops.

**Comment by simondeschenes** [comment]
I looked at the latest merge and it is effectively partially fixed. See previous post.

**Comment by boberfly** [comment]
Just to add to this, this is crashing on Linux on this line:
https://github.com/ConfettiFX/The-Forge/blob/master/Common_3/Renderer/Vulkan/Vulkan.cpp#L2533
I tried the things @simondeschenes suggests but it still crashes. I haven't spent much time on this to investigate.

Cheers!

**Comment by boberfly** [comment]
Disregard this, it was just an issue on my side not passing #define VULKAN, it works with/without the tweak from @simondeschenes

**Comment by wolfgangfengel** [comment]
@simondeschenes this should be resolved with the next release, probably next week ... if you have a chance check it out and then we can close this.

**Comment by simondeschenes** [comment]
As soon as I see the code online I'll check it out.

**Comment by wolfgangfengel** [comment]
It is up now ... let us know ....
